### ISSUE TITLE
Compile error: __open_missing_mode declared with attribute error

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#75]
I'm running `gcc version 11.2.0 (Ubuntu 11.2.0-7ubuntu2)` on Pop!_OS 21.10:

```In file included from /usr/include/fcntl.h:314,
                 from /usr/include/x86_64-linux-gnu/sys/file.h:24,
                 from src/keyd.c:35:
In function ‘open’,
    inlined from ‘daemonize’ at src/keyd.c:769:7,
    inlined from ‘main’ at src/keyd.c:847:3:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:11: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
   50 |           __open_missing_mode ();
      |           ^~~~~~~~~~~~~~~~~~~~~~
```

I believe the fix is similar to https://github.com/facebook/hhvm/commit/f55604ba3d916ab39354af67852583ec79038710

**Comment by eNV25** [comment]
In Arch Linux AUR package this happens because of `-Wp,-D_FORTIFY_SOURCE=2` in `/etc/makepkg.conf` `CFLAGS=`. I suspect this is similar here.

c7aff2afea37988c131ed441197faec5cb5234f2 seems to have introduced this issue. (Using `git bisect`).

**Comment by eNV25** [comment]
CFLAGS from `/etc/makepkg.conf` (pacman 6.0.1-2).

```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
```

Build command:

```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection" make
```

**Comment by rvaiya** [comment]
Oops. This should be fixed.
